name: 'VitoDeploy Review-app Clean Action'
description: 'Clean a review-application on VitoDeploy'
author: 'rygilles'

branding:
  icon: upload-cloud
  color: red

inputs:
  api_base_url:
    description: 'API URL (e.g.: "https://vito.test/api")'
    required: true
  api_token:
    description: 'API key'
    required: true
  project_id:
    description: 'Project ID'
    required: true
  server_id:
    description: 'Server ID'
    required: true
  root_domain:
    description: 'Root domain under which to create review-app site'
    required: false
  host:
    description: 'Site host of the review-app'
    required: false
  prefix_with_pr_number:
    description: 'Use the pull-request number as host and database prefix when host is not manually defined'
    required: false
    default: 'true'
  fqdn_prefix:
    description: 'Prefix the whole FQDN (e.g.: "app.")'
    required: false
  pr_number:
    description: 'Manually define pull-request number'
    required: false
  database_name:
    description: 'Database name of the review-app site'
    required: false
  database_name_prefix:
    description: 'Database name prefix, useful for PostgreSQL that does not support digits (PR number) for first chars'
  debug:
    description: 'Enable debug mode.'
    required: false
    default: 'false'

outputs:
  host:
    description: 'Host of the review-app (generated or forced one in inputs)'
  database_name:
    description: 'Database name of the review-app (generated or forced one in inputs)'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_API_BASE_URL: ${{ inputs.api_base_url }}
    INPUT_API_TOKEN: ${{ inputs.api_token }}
    INPUT_PROJECT_ID: ${{ inputs.project_id }}
    INPUT_SERVER_ID: ${{ inputs.server_id }}
    INPUT_HOST: ${{ inputs.host }}
    INPUT_PREFIX_WITH_PR_NUMBER: ${{ inputs.prefix_with_pr_number }}
    INPUT_FQDN_PREFIX: ${{ inputs.fqdn_prefix }}
    INPUT_PR_NUMBER: ${{ inputs.pr_number }}
    INPUT_DATABASE_NAME: ${{ inputs.database_name }}
    INPUT_DATABASE_NAME_PREFIX: ${{ inputs.database_name_prefix }}
    INPUT_DEBUG: ${{ inputs.debug }}
